import type { Metadata } from 'next'
import './globals.css'
import { primaryFont } from '@/config/fonts'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='es' className={`${primaryFont.variable}`}>
      <body className='antialiased'>
        <main>{children}</main>
      </body>
    </html>
  )
}
