import type { Metadata } from 'next'
import './globals.css'
import { publicFont } from '@/config/fonts'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${publicFont.variable} antialiased`}>{children}</body>
    </html>
  )
}
