import type { Metadata } from 'next'
import './globals.css'
import { primaryFont } from '@/config/fonts'
import Header from './components/ui/header'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='es' className={`${primaryFont.variable}`}>
      <body className='antialiased'>
        <header>
          <div className='logo primary-font font-bold'>CENSAO</div>
        </header>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  )
}
